import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/header'
import Footer from '../component/footer'
import Homee from '../component/home'
import axios from 'axios'
import { wrapper } from '../store/store';
import { autodiggSlice, setCars } from '../slice/slice';
import { useSelector } from 'react-redux'


const api_url = "https://autodigg.com/ad-api/cars/list?usedCar=true&car_type=Used+car&page=1&radius=100&year=2011,2021&zip=&price_from=0&price_to=100000";

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
  const api = await axios.all([
    axios.get(api_url),
    axios.get(`${api_url}&return=count`),
    axios.get(`${api_url}&return=body_type`),
    axios.get(`${api_url}&return=exterior_color`),
    axios.get(`${api_url}&return=interior_color`),
    axios.get(`${api_url}&return=transmission`),
    axios.get(`${api_url}&return=drivetrain`),
    axios.get(`${api_url}&return=fuel_type`),
    axios.get(`${api_url}&return=features`),
    axios.get(`${api_url}&return=make`),
    axios.get(`${api_url}&return=model`)
  ]);
  if (api) {
    store.dispatch(setCars({
      cars: api[0].data,
      count: api[1].data.count,
      body_type: api[2].data,
      exterior_color: api[3].data,
      interior_color: api[4].data,
      transmission: api[5].data,
      drivetrain: api[6].data,
      fuel_type: api[7].data,
      features: api[8].data,
      make: api[9].data,
      model: api[10].data
    }));
  }
});

export default function Home() {

  const carData = useSelector((state) => state.autodigg.count);
  return (
    <div className='bg-[#FAFAFC] max-w-[1440px] mx-auto  '>
      <Header />
      <div className='flex flex-col px-[60px] gap-[8px] py-[36px]'>
        <label className='text-[#8F90A6] font-semibold text-[12px] leading-[16px] not-italic '> USED CARS FOR SALE</label>
        <label className='text-[#28293D] not-italic font-bold text-[32px] leading-[44px]'>Showing {carData.toLocaleString('en-US')} cars</label>
      </div>
      <Homee />
      <Footer />
    </div>
    // <Header />

    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>
    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}

